### ISSUE TITLE
Please upload it to npm

### ISSUE THREAD

**Issue by AxelMarquez** [ngx-material-keyboard/core#12]
Hello!

This is a very nice keyboard! it would be perfect if you could upload it to npm (*^_^*)

**Comment by davidenke** [comment]
Yes, that is definitly on schedule. But I wanted to wait for a more stable version with a minimal feature set. I'll find some time on friday to plan missing features to create a roadmap, or some milestones at least...

**Comment by davidenke** [comment]
The project is [published](https://www.npmjs.com/package/@ngx-material-keyboard/core).
