### ISSUE TITLE
If the input is in the bottom the keyboard covers it

### ISSUE THREAD

**Issue by AxelMarquez** [ngx-material-keyboard/core#13]
If the input is in the lower bounds of the screen the keyboard will cover it and the user won’t be able to see what he’s typing.
The simplest solution would be to show the keyboard on top if the input is in the lower bounds of the screen.

**Comment by davidenke** [comment]
The question is, if this behavior couldn't be fixed by the layout of the form itself. Wouldn't it be more useful to add some space behind the keyboard to enlarge the page?

**Comment by AxelMarquez** [comment]
I think the most useful would be to handle it as a floating element (instead of being docked at the bottom) take for example Angular material design’s [datepicker](https://material.angular.io/components/datepicker/overview) (also note that the scroll is disabled when the datepicker is shown to avoid the input going out of sight if user scrolls).

However, if you think that this should be handled by the consumer of your keyboard it would be necessary to give an option to specify in which DOM element will the keyboard be rendered, as in [Issue 7](https://github.com/ngx-material-keyboard/core/issues/7).

**Comment by davidenke** [comment]
Imho it's a bit distracting if the keyboard 'jumps' from input to input. But I think it should be a feature to be enabled optionally...

**Comment by davidenke** [comment]
I would recommend to use a component which is designed for that usage, e.g. [stephen31/virtual-keyboard-plugin](https://github.com/stephen31/virtual-keyboard-plugin).
