### ISSUE TITLE
'AnimationEvent' was not found in '@angular/animations'

### ISSUE THREAD

**Issue by waldekm** [ngx-material-keyboard/core#2]
When I use your library with Angular 4 I get the following warning:
WARNING in ./~/ngx-material-keyboard/src/components/keyboard-container.component.ts
130:61-75 "export 'AnimationEvent' was not found in '@angular/animations'

I have "@angular/animations": "^4.3.0", becouse  4.1.2 doesn't work with Angular 4.
Do you have maybe any idea how to solve this problem?

**Comment by davidenke** [comment]
I experienced this issue too. If I find some time I'll update the dependencies in a new release.

**Comment by davidenke** [comment]
I tried an alternative import, now this issue seems solved.
