### ISSUE TITLE
Need to adjust position of keyboard

### ISSUE THREAD

**Issue by danclegg** [ngx-material-keyboard/core#23]
After applying the keyboard to my project as the demo project does, but without all the switches and options, the keyboard only appears at the top of my UI when active. I'd like to force it to the bottom, or (more generally) declare the keyboard position.

**Comment by davidenke** [comment]
I think this is related to #13.

**Comment by tomo-it** [comment]
Adding the keyboard to a dom element would be very usefull for me as well.

**Comment by davidenke** [comment]
s. #13.
