### ISSUE TITLE
npm i --save @ngx-material-keyboard/core installs @ngx-material-keyboard/demo

### ISSUE THREAD

**Issue by stevebelt** [ngx-material-keyboard/core#26]
I am following the newly updated README.md instructions (for which I thank you!). From the command line, when I enter npm i --save @ngx-material-keyboard/core I get the following output:

```
$ npm i --save ngx-material-keyboard/core

[... deleted some unrelated warnings here ...]
> @ngx-material-keyboard/demo@0.0.7-SNAPSHOT postinstall C:\development\workspace-c2marts\C2MArts-Client\node_modules\@ngx-material-keyboard\demo
> npm rebuild node-sass

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","a
rch":"x64"})

+ @ngx-material-keyboard/demo@0.0.7-SNAPSHOT
added 131 packages in 62.22s
```

Now in my node_modules I have @ngx-material-keyboard/demo/, but not core/

**Comment by davidenke** [comment]
Sorry, I can't reproduce, everything works as expected:
1. went to a different machine (Windows 10), without being locked in to npm
2. created a fresh angular 5.0.3 application using the CLI (1.5.2)
3. installed using `npm i --save @ngx-material-keyboard/core`

After that I had everything installed in `node_modules\@ngx-material-keyboard\core`.

**Comment by davidenke** [comment]
@stevebelt today I was able to reproduce this bug and fixed it ;)
