### ISSUE TITLE
Not able to bind formControlName with keyboard

### ISSUE THREAD

**Issue by sukhdeepsingh123** [ngx-material-keyboard/core#35]
hey,
I am not able to bind reactive form with the keyboard.Even basic input attributes like max length does not work.Please help

**Comment by sachin15aug94** [comment]
use (focusout)="loginForm.controls['username'].setValue($event.target.value)" when using formControlName. It solved the issue temporarily. You can also validate on focusout event, as it is the only event we can capture.

**Comment by davidenke** [comment]
The whole event handling isn't finished yet, I hope I#ll have time to improve it in the next weeks.
