### ISSUE TITLE
the keyboard is breaking with materialize css

### ISSUE THREAD

**Issue by masrc** [ngx-material-keyboard/core#36]
Hey, I'm using ngx-material-keyboard, without materialize css it works fine, but installing materialize in my project, is breaking... for reproduce this error, you just need install materialize, ngx-material-keyboard and try to use, when the keyboard open, it is be breaked. Can you help me fix this?

**Comment by davidenke** [comment]
Hi @masrc,

this is not a Materialize component and therefor it’s not intended to work without the Angular Material Framework.

**Comment by masrc** [comment]
Yeah, I know, but this means that I can't use ngx-material-keyboard if I use Materialize in my others components, even with Angular Material installed?

**Comment by davidenke** [comment]
@masrc to be honest I'm surprised that it _does_ really work. I can imagine that mixing two completely different frameworks has its reasons for your case, but it is not intended to create a Angular Material Component and test it against different frameworks...

If there is an error (and I'm sure this component in it's current state will have [m]any :), provide a plunker and a bit more steps to reproduce. And most important: does the error occur without possible side-effects from a different framework?

**Comment by masrc** [comment]
Ahh, I get it! but really no side-effects, just the breaked template of keyboard even.
