### ISSUE TITLE
Get the value typed on the keyboard

### ISSUE THREAD

**Issue by masrc** [ngx-material-keyboard/core#38]
Hey, I have a very simple application. There I have a text-editor and I need use ngx-material-keyboard to write on it, but I dont know how to get the value to pass for binding.

I open the keyboard with a method like in your exemple, so that is not automatic. I maked a demo and it can be usefull, you just need run npm install and it should work fine

[demoKeyboard.zip](https://github.com/ngx-material-keyboard/core/files/1646455/demoKeyboard.zip)

Can I do something like that? How?

**Comment by davidenke** [comment]
Hi @masrc, could you please provide a plunkr describing your setup?

**Comment by davidenke** [comment]
Closing for now due to missing answer.
