### ISSUE TITLE
Customize Keyboard Layout

### ISSUE THREAD

**Issue by Alex66955** [ngx-material-keyboard/core#4]
Is there a way to customize the keyboard layout? I want to run this keyboard on a small screen device and the responsive design is not working for 480x272 px correctly.
![image](https://user-images.githubusercontent.com/3258379/28859865-38e0ed52-775a-11e7-830c-d41729cb3dac.png)

**Comment by davidenke** [comment]
You mean to add a custom button layout or change the dimensions of the keyboard and it's components? For customizing the layout itself have a look [here](https://github.com/ngx-material-keyboard/core/issues/5#issuecomment-319800294).

**Comment by Alex66955** [comment]
> You mean to add a custom button layout or change the dimensions of the keyboard and it's components? 

I mean changing the dimension of the whole keyboard. At the moment I'am not able to use it on a small display 480x272. I changed the css style attributes in the source code but I can't get enough space to get the whole keyboard on the screen (alphanumeric).
The goal is to provide an on screen keyboard on a mobile device without hardware keys.

Do you have any suggestions on which sections in your source code I have to make changes?

**Comment by davidenke** [comment]
@Alex66955 you should have a look at the assigned css classes and the component selector names. It should be possible to override the css properties globally:
```css
.mat-keyboard .mat-raised-button {
  font-size: 13px;
  line-height: 16px;
  padding: 0 8px;
}
```
Have a look at this [Plunker](https://embed.plnkr.co/pULfCCcfh3mEsMK5p4ab/).

**Comment by Alex66955** [comment]
Thank you for the fast response.

The origin implementation has a nice responsive design regardless of the screen dimension --> https://cdn.rawgit.com/davidenke/angular-material-keyboard/0.0.8/demo.html

![image](https://user-images.githubusercontent.com/3258379/29121878-a7a6ae96-7d10-11e7-9394-5fdc930d33c2.png)

**Comment by Alex66955** [comment]
I found the perfect configuration for me. It let your design untouched but if you decrease the screen size the whole keyboard is flexible.

At the moment I'am only able to adjust that modification in my web browser.
I have to adjust these "keyboard-container.component.scss". With your suggested solution I'am not able to change them. There are still shown in my browser dev tools 
`
..
max-width: $mat-keyboard-max-width;

min-width: $mat-keyboard-min-width;

padding: $mat-keyboard-padding;
..
`

**Comment by maverick70192** [comment]
> Thank you for the fast response.
> 
> The origin implementation has a nice responsive design regardless of the screen dimension --> https://cdn.rawgit.com/davidenke/angular-material-keyboard/0.0.8/demo.html
> 
> ![image](https://user-images.githubusercontent.com/3258379/29121878-a7a6ae96-7d10-11e7-9394-5fdc930d33c2.png)

can you give me the code?

**Comment by zeynepgk3** [comment]
> > Thank you for the fast response.
> > The origin implementation has a nice responsive design regardless of the screen dimension --> https://cdn.rawgit.com/davidenke/angular-material-keyboard/0.0.8/demo.html
> > ![image](https://user-images.githubusercontent.com/3258379/29121878-a7a6ae96-7d10-11e7-9394-5fdc930d33c2.png)
> 
> can you give me the code?

hey, did you get the code?
