### ISSUE TITLE
angular/cdk/portal has not BasePortalOutlet

### ISSUE THREAD

**Issue by Tora-Bora** [ngx-material-keyboard/core#40]
Hi, I have an error, while ng build:
ERROR in node_modules/@ngx-material-keyboard/core/components/keyboard-container/keyboard-container.component.d.ts(2,10): error TS2305: Module '"D:/AngularInterface/node_modules/@angular/cdk/portal"' has no exported member 'BasePortalOutlet'.

**Comment by davidenke** [comment]
Hi, could you provide steps to reproduce, or a plunkr?

**Comment by jderboven** [comment]
Had the same issue and as far as I can see, the package seems to be angular 5 only so if your app is in angular 4 or lower than 5, it won't work

**Comment by davidenke** [comment]
Right, that should produce warning on `npm install`, see [peer dependencies](https://github.com/ngx-material-keyboard/core/blob/master/src/core/package.json)

**Comment by jderboven** [comment]
Any chance it gets ported to ng4 ?

**Comment by davidenke** [comment]
Basically it's not the Angular version in the first place. The CDK has to support it and related to that version you maybe can use Angular 4. But the Material and CDK modules have just been relased stable and I don't think it would be useful to provide support downwards to beta or rc releases.
