### ISSUE TITLE
Subscribe to any key clicked on the on screen keyboard

### ISSUE THREAD

**Issue by jamhall** [ngx-material-keyboard/core#41]
Hello.

Excellent module! 

I know you can bind the keyboard to an input instance, however, for my use case, I don't have an input element. I would like to subscribe to the keys clicked and then pass that key event onto something else. 

I see you have `enterClick`, `capsClick`, `altClick`,  `shiftClick` event emitters, it would be nice to also have a generic `click` (for any key) emitter. 

If this is not currently possible, I will happily contribute to the code base.

Thank you so much!

**Comment by davidenke** [comment]
@jamhall good idea. I added the missing Outputs and added a "generic" event to listen to all keyboard events.

**Comment by jamhall** [comment]
@davidenke you did that quickly! 😆 thank you so much! Have a good day.

**Comment by laura-chesches** [comment]
can you please tell me how to use the generic event that you said it's added?
 I want to override the click method, so every time a key is pressed to make it uppercase, for example. all the events (keuUp, mouseUp, mouseDown) are listened by the input, but not by the keyboard
