### ISSUE TITLE
Removing the animations and fixing the keyboard to the bottom

### ISSUE THREAD

**Issue by ShrekTheHumper** [ngx-material-keyboard/core#48]
Hi,
Is there a way to remove the animations?
I am also wondering if there is a way to fix the keyboard to the bottom centre of the page.

**Comment by davidenke** [comment]
To remove animations it should be possible to deactivate them as documented in the [Material docs](https://material.angular.io/guide/getting-started#step-2-animations).
The keyboard is always centered and on the bottom, or did I misunderstand you @ShrekTheHumper?

**Comment by ShrekTheHumper** [comment]
The keyboard appears under the content at the bottom of the page. Is there any way to "dock" it at the bottom of the page?

**Comment by davidenke** [comment]
Usually it is on top of the content at the bottom of the viewport. If not, your layout is a bit "special". The keyboard is attached using the cdk, so your layout may also break with all other Material components using  it.
Could you provide a plunkr showing your basic layout? Have you tried using the layout examples from the Material docs?

**Comment by ShrekTheHumper** [comment]
The thing is that i dont use material, i use bootstrap. I was unable to find any other working keyboards for angular, so i ended up with this one (Which i got working after a while). I just upgraded from 0.0.11 to 0.1.0 and have another issue now. Is this because i dont use the material containers etc?

![image](https://user-images.githubusercontent.com/31448564/36977143-70cdc562-2080-11e8-9f83-1ccb14f7660a.png)

**Comment by davidenke** [comment]
Sorry, without a Plunkr it's not reproducable.

**Comment by davidenke** [comment]
It'll be reopened if it is reproducible.

**Comment by onlineuser1825** [comment]
Can we customize the keyboard position

**Comment by FloLech** [comment]
I had the same issue and solved it by adding the following to the cdk-overlay-container CSS class

`.cdk-overlay-container {
  position: fixed;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
}`
