### ISSUE TITLE
ngx-material-virtual keyboard is not supporting keyup events

### ISSUE THREAD

**Issue by ghost** [ngx-material-keyboard/core#52]
I'm using Virtual Keyboard for my one of Angular Project where i want to use keyUp event for input validation but not able to use keyup/keydown/keypress any events for virtual keyboard .Events are working fine for hardware Keyboard so there is no syntax error.
<input class="search type="text" matInput [matKeyboard]="'Azərbaycanca'"
placeholder="Search for a song" (keyup.enter)="search_result();(enterClick)="closeCurrentKeyboard();" (keyup)="function();">

https://github.com/ngx-material-keyboard/core
I had tried a lot of substitute but not able to get perfect solution.Please help me with Solution

**Comment by lizylgit** [comment]
I am using  ngModel and ngModelChange 

<input type="text" class="form-control" id="location-search" type="text"  matInput
           matKeyboard
           [(ngModel)] = "searchValue"
           (ngModelChange)="searchLocation($event)">

**Comment by mitalthakkar31** [comment]
@lizylgit Thanks for the answer
But I had also tried  ngModel and ngModelChange options but still on input change (if input is entered by virtual Keyboard) function is not calling.

**Comment by tamitam** [comment]
Did you find a solution that works?

**Comment by lizylgit** [comment]
This  solution did not work on the device (signage) we were planning to implement. When I tested with PC it worked fine. 
You could try this JS solution which i had explored a bit: https://www.npmjs.com/package/virtual-keyboard-plugin

I didn't implement either of these virtual keyboard solution,  got the device vendor (signage) to provide with a virtual keyboard solution.
