### ISSUE TITLE
I want to close keyboard on enter click in same component

### ISSUE THREAD

**Issue by ghost** [ngx-material-keyboard/core#53]
I had used this ngx-material-keyboard in one of my project i want to add search input when search terms were entered using virtual keyboard and then after clicking enter keyboard should be disappear and search result should be appear but i am giving search list in same component so keyboard is retaning as it is after clicking enter.

My code is as below:

html----->
  <input class="search" 
                  type="text" 
                  matInput  
                  [matKeyboard]="'Azərbaycanca'"     
                  placeholder="Search for a song"
                  (keyup.enter)="search_result();"   
             >   
app.component.ts-->
search_result(){
  this.router.navigate(['/general/searchResult']);   
}

Please help me with solution or substitute of solution.

**Comment by Enoch-Ye** [comment]
Hi, have you tried dismiss method on MatKeyboardService? 
https://ngx-material-keyboard.github.io/core/injectables/MatKeyboardService.html#dismiss
