### ISSUE TITLE
How To give input keyboard language option 

### ISSUE THREAD

**Issue by ghost** [ngx-material-keyboard/core#54]
Hello,
          I want to add one input box in which i can enter text but i need number of Language option from virtual keyboard for that particular Input. I had used demo code as provided in Git Demo but Language Keyboard is appearing on button click same click functionality added by me on input but not able to add input just clicking on input different Language Keyboard is appearing.

Following is my Code.Please help me with solution
  <input class="search" 
                  type="text" 
                  matInput  
                  [matKeyboard]="'locale'"    
                  (click)="openKeyboard(locale)" 
                  placeholder="Search for a song">

<mat-select
      class="language"
      name="layout"
      [placeholder]="'select layout'"
      [(ngModel)]="locale">

  <mat-option
         class="language_option"
        *ngFor="let layout of layouts"
        [value]="layout.layout.lang && layout.layout.lang[0] || layout.name">
       {{layout.layout.name}}
  <ng-container *ngIf="layout.layout.name !== layout.name">({{layout.name}})</ng-container>
  </mat-option>
</mat-select>

**Comment by tamitam** [comment]
Hi,
Did you find a solution? I got this problem too....
