### ISSUE TITLE
Angular material version isn't flexible

### ISSUE THREAD

**Issue by janos-roche** [ngx-material-keyboard/core#58]
The angular material version is not flexible in package.json

```
"@angular/material": "5.2.2",
```

was it possible to change it to

```
"@angular/material": "^5.2.2",
```

**Comment by joernweissenborn** [comment]
I don't think this can be done as easy like this, at least not if you want it to use with a major upgrade like angular 6.x. Alot of background dependencies are changed (escpecially rxjs) and things in angular itself like services. 

@davidenke: I am willing to contribute to make the keyboard angular 6.x compatible if you are not working not working on it already. Nice work by the way!

**Comment by davidenke** [comment]
@joernweissenborn sounds great. Honestly, I don't have enough time right now for this project so every support is welcome.

**Comment by janos-roche** [comment]
@davidenke could you then open up the contributor's list please? Or would you prefer to have your project forked and the open the PR from the fork?

**Comment by davidenke** [comment]
@janos-roche I prefer PRs because it allows to enforce some code quality. But if you have look to the already opened PRs and their age, you'll see that I still didn't managed it yet to review them.
Would you mind to contribute with a PR first? It would be nice to add some collaborators later on...

**Comment by davidenke** [comment]
I prefer PRs because it allows to enforce some code quality. But if you have look to the already opened PRs and their age, you'll see that I still didn't managed it yet to review them.
Would you mind to contribute with a PR first? It would be nice to add some collaborators later on...

**Comment by nallarv** [comment]
@davidenke, I forked your code and updated it to be flexible for minor upgrades with the below mentioned dep's. Can you use this as an interim before upgrading to 6?
`
"dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "classlist.js": "1.1.20150312",
    "core-js": "^2.5.3",
    "hammerjs": "^2.0.8",
    "reset-css": "2.2.1",
    "rxjs": "^5.5.2",
    "web-animations-js": "2.3.1",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.7.0",
    "@angular/compiler-cli": "^5.2.9",
    "@angular/language-service": "^5.2.9",
    "@compodoc/compodoc": "^1.0.7",
    "@types/jasmine": "~2.8.6",
    "@types/node": "~9.4.6",
    "codelyzer": "^4.1.0",
    "cpx": "1.5.0",
    "ng-packagr": "^2.1.0",
    "rxjs-tslint-rules": "3.14.0",
    "sass-lint": "^1.12.1",
    "ts-node": "~5.0.0",
    "tslint": "^5.9.1",
    "typescript": "~2.6.2"
  }
`

**Comment by davidenke** [comment]
@nallarv What I meant earlier is that if you unpin the dependencies you _have to_ ensure that this project at least works against all minor releases within the version range. And that means integrating something like Travis CI to automate it and, of course, having some unit tests (and eventually smoke e2e tests). Unfortunately we have none yet.

**Comment by joernweissenborn** [comment]
@davidenke Ok, I will take a look into the 6.x issues. From first glance it is the typical API change issues, but mostly with rsjx stuff. I will take a deeper look later this week and report my findings. Maybe we should open another ticket for this?

**Comment by davidenke** [comment]
s. #73.
