### ISSUE TITLE
Enable or Disable virtual keyboard using property in MatKeyboardService

### ISSUE THREAD

**Issue by amarnatha24** [ngx-material-keyboard/core#67]
Can you implement Enable or Disable virtual keyboard using property in MatKeyboardService, It would be useful for user to enable or disable whenever they don't need virtual keyboard.

**Comment by davidenke** [comment]
You could disable the behaviour by wrapping the keyboard service with your own service. Then it is completly up to you on which circumstances you have to toggle.

**Comment by amarnatha24** [comment]
Thanks.
