### ISSUE TITLE
How can i add the back space button to my layout?

### ISSUE THREAD

**Issue by fott1** [ngx-material-keyboard/core#69]
```const customLayouts: IKeyboardLayouts = {
  ...keyboardLayouts,
  'custom_layout': {
    'name': 'namehere',
    'keys': [
      [
        ['1', '!'],
        ['2', '@'],
        ['3', '#'],
        ['4', '$'],
        ['5', '%'],
        ['6', '&'],
        ['7', '*'],
        ['8', '('],
        ['9', ')'],
        ['0', ';'],
        ['Back space here', 'Back space here'],
      ],
      [ 
        [' ', ' '] 
      ]
    ],
    'lang': ['en-US']
  }
};```

How can i add the back space button to the above custom layout?

**Comment by davidenke** [comment]
Just use `KeyboardClassKey.Space` from the [KeyboardClassKey](https://github.com/ngx-material-keyboard/core/blob/master/src/core/src/enums/keyboard-class-key.enum.ts)! :)

There's an [`KeyboardModifier`](https://github.com/ngx-material-keyboard/core/blob/master/src/core/src/enums/keyboard-modifier.enum.ts) for the modifier keys as well.
For example: https://github.com/ngx-material-keyboard/core/blob/master/src/core/src/configs/keyboard-layouts.config.ts#L173-L174

**Comment by fott1** [comment]
Excellent! Thank you, it would be great to have it in the docs.

**Comment by davidenke** [comment]
@fott1 feel free to contribute and PR! 🥇
