### ISSUE TITLE
Change keyboard container

### ISSUE THREAD

**Issue by offwork** [ngx-material-keyboard/core#7]
Is it possible to open the keyboard in a container we want?

**Comment by davidenke** [comment]
It should be. I hope to find some time to implement the usage of @angular/cdk to inject the keyboard dynamicly (like in the material dialog service), then it would be quite easy to give an optional view container reference.
Would also like to review a PR, though... 😆

**Comment by offwork** [comment]
I do not understand what's funny.

**Comment by davidenke** [comment]
@offwork Then you lack the sense of humor.

**Comment by offwork** [comment]
look I'm laughing now 😆 😆 😆
