### ISSUE TITLE
OSK's behavior with input fields in modals

### ISSUE THREAD

**Issue by n3phtys** [ngx-material-keyboard/core#70]
I am combining this with [ngx-modialog](https://github.com/shlomiassaf/ngx-modialog), using the Bootstrap plugin.
I would like to have a prompt I can write to with the OSK, but the OSK appears below the modal. If the modal is blocking I cannot touch the OSK, and if it isn't, loosing the focus will lead to the modal being removed.

I am wondering if there is a way to move the OSK up to the modal's outer div so it will appear within it, being useful without loosing the modal's focus?

Thanks in advance.

PS: I am also fine with changing any library here if someone has a solution using other options :)

**Comment by davidenke** [comment]
That is managed by the CDK. I think the easiest was is to override the `z-Index` with CSS...
