### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by jderboven** [ngx-material-keyboard/core#74]
When taking back the code to upgrade it to NG-6, we get the following messages : 

WARNING in Circular dependency detected:
..../modules/keyboard/services/keyboard.service.ts -> .../modules/keyboard/components/keyboard/keyboard.component.ts -> .../modules/keyboard/services/keyboard.service.ts

**Comment by davidenke** [comment]
Angular 6 support is not yet implemented.
