### ISSUE TITLE
Don't work on IE 11

### ISSUE THREAD

**Issue by AugustoFaria** [ngx-material-keyboard/core#76]
Hello im trying to use ngx-material-keyboard on IE 11 is it possible?

I already polyfill the project to use IE 11. My project is on Angular 5.

Im getting this error when i click on some keyboard button 
ERROR TypeError: Object does not support action

In Chrome and Microsoft Edge works Ok but IE 11 nope, and the front-end need to work on IE11 :(.

My code using matKeyboard directive:
 <input class="form-control form-control-lg" 
 [matKeyboard]="'upperCaseLayout'" placeholder="NOME" type="text" formControlName="fName" 
 required>

Please help.
Regards

**Comment by davidenke** [comment]
Could you provide the complete error message, please?

**Comment by raghurambandaru03** [comment]
> Hello im trying to use ngx-material-keyboard on IE 11 is it possible?
> 
> I already polyfill the project to use IE 11. My project is on Angular 5.
> 
> Im getting this error when i click on some keyboard button
> ERROR TypeError: Object does not support action
> 
> In Chrome and Microsoft Edge works Ok but IE 11 nope, and the front-end need to work on IE11 :(.
> 
> My code using matKeyboard directive:
> <input class="form-control form-control-lg"
> [matKeyboard]="'upperCaseLayout'" placeholder="NOME" type="text" formControlName="fName"
> required>
> 
> Please help.
> Regards

got same issue

error: ERROR TypeError: Object does not support action

**Comment by davidenke** [comment]
To be honest the error messages of IE11 are ridiculous. I think that there's missing a polyfill. Have you tried to enable all features of `core-js` in the `polyfills.ts` in your host app?

**Comment by raghurambandaru03** [comment]
> To be honest the error messages of IE11 are ridiculous. I think that there's missing a polyfill. Have you tried to enable all features of `core-js` in the `polyfills.ts` in your host app?

Thanks for your reply .
I enabled all required polyfills:

please check this:


/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
 import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
 import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';


/**
 * Web Animations `@angular/platform-browser/animations`
 * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
 * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

 // (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 // (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 // (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames

 /*
 * in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 * with the following flag, it will bypass `zone.js` patch for IE/Edge
 */
// (window as any).__Zone_enable_cross_context_check = true;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */


Let me know anything should be added in this file?

**Comment by davidenke** [comment]
Just try to load all of core-js by replacing the specific imports with just `import 'core-js';`.

**Comment by raghurambandaru03** [comment]
> import 'core-js';

Tried with this  import 'core-js';          but same issue 

<img width="959" alt="capture11" src="https://user-images.githubusercontent.com/38371339/49802382-bdf74c80-fd72-11e8-9bfd-76f935c298f3.PNG">

**Comment by davidenke** [comment]
Could you dig deeper and expand the messages, or find some place in the code where it has been thrown or even a line number?

**Comment by raghurambandaru03** [comment]
> Could you dig deeper and expand the messages, or find some place in the code where it has been thrown or even a line number?

hi David , tried to debug the error  in ie(internet explorer), but its very difficult find from where the error is coming , but the error is occuring when pressing the key on keyboard. 
or you can ping me in skype:  live:5207bd0ec6bb98d6  , so that i can share my screen to show you once .

<img width="447" alt="capture12" src="https://user-images.githubusercontent.com/38371339/49865320-a5e30400-fe2a-11e8-8961-5926cd91aeac.PNG">

**Comment by davidenke** [comment]
It looks like you're missing to import smth. of rxjs.
Please provide a Plunkr or Stackblitz to reproduce.

**Comment by raghurambandaru03** [comment]
> It looks like you're missing to import smth. of rxjs.
> Please provide a Plunkr or Stackblitz to reproduce.

thanks for responding,
what is smth of rxjs?  i  am already using rxjs in my application

**Comment by davidenke** [comment]
We'll see in the reproduction code.

**Comment by raghurambandaru03** [comment]
> We'll see in the reproduction code.

Even the demo ngx-material-keyboard is having same issue ie please open the below demo url in IE , its showing same error.(press the keys and check in console)
Demo url :    https://ngx-material-keyboard.github.io/demo/

![image](https://user-images.githubusercontent.com/38371339/49886570-00e31e00-fe60-11e8-93b8-357fa144d58f.png)


![image](https://user-images.githubusercontent.com/38371339/49886988-27ee1f80-fe61-11e8-9fb5-fdcf05efff2b.png)

**Comment by raghurambandaru03** [comment]
> > We'll see in the reproduction code.
> 
> Even the demo ngx-material-keyboard is having same issue ie please open the below demo url in IE , its showing same error.(press the keys and check in console)
> Demo url : https://ngx-material-keyboard.github.io/demo/
> 
> ![image](https://user-images.githubusercontent.com/38371339/49886570-00e31e00-fe60-11e8-93b8-357fa144d58f.png)
> 
> ![image](https://user-images.githubusercontent.com/38371339/49886988-27ee1f80-fe61-11e8-9fb5-fdcf05efff2b.png)

any solution  ???????????????????????????
