### ISSUE TITLE
How to hide the ngx-material-keyboard permanently on mobile views?

### ISSUE THREAD

**Issue by codersree** [ngx-material-keyboard/core#78]
Hi I'm using ngx-material keyboard in one of my projects. I have an input which can be entered in two languages based on a radio button toggle. Languages are English and Malayalam. Both layouts are entered and keyboards are showing without any problem. However I need it to be disabled on English language selection and show the keyboard only when Malayalam option is selected. How can I do that? And how to permanently disable the virtual keyboard on mobile views?

**Comment by davidenke** [comment]
You can control the keyboard by using the service. Have a look inside the directive [which calls the service](https://github.com/ngx-material-keyboard/core/blob/master/src/core/src/directives/keyboard.directive.ts#L41-L45) internally too.
